apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
  - name: "http"
    port: 8090
    targetPort: 8080
    nodePort: 30181
  selector:
    io.kompose.service: keycloak
  type: NodePort
