apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      nodeSelector:
        name: min01
      containers:
      - args:
        - -b 0.0.0.0 --server-config=standalone.xml
        env:
        - name: KEYCLOAK_ENVIRONMENT
          value: /etc/secrets/keycloak.env
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_password
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_user
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_pass
        - name: MYSQL_PORT_3306_TCP_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_host
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: WAIT_ON_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_host
        - name: WAIT_ON_PORT
          value: "3306"
        image: quay.io/ukhomeofficedigital/keycloak-mysql:v3.1.0
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/secrets/keycloak.env
          name: keycloak-env
        - mountPath: /opt/jboss/keycloak/themes/govuk/
          name: keycloak-govuk
        - mountPath: /opt/jboss/keycloak/themes/govuk-internal/
          name: keycloak-govuk-int
        - mountPath: /opt/jboss/keycloak/themes/govuk-social-providers/
          name: keycloak-govuk-soc
        - mountPath: /opt/jboss/keycloak/themes/govuk-egar/
          name: keycloak-govuk-egar
        - mountPath: /opt/jboss/keycloak/keycloak-db.json
          name: keycloak-db
        - mountPath: /opt/jboss/keycloak/standalone/data/password-blacklists/
          name: passwdblack
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloakdata
      restartPolicy: Always
      volumes:
        - name: keycloak-env
          hostPath:
            path: /root/keycloak.env
        - name: keycloak-govuk
          hostPath:
            path: /root/govuk
        - name: keycloak-govuk-int
          hostPath:
            path: /root/govuk-internal
        - name: keycloak-govuk-soc
          hostPath:
            path: /root/govuk-social-providers
        - name: keycloak-govuk-egar
          hostPath:
            path: /root/govuk-egar
        - name: passwdblack
          hostPath:
            path: /root/password-blacklists
        - name: keycloak-db
          hostPath:
            path: /root/keycloak-db.json
        - name: keycloakdata
          hostPath:
            path: /root/keycloakdata
status: {}
