apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ports:
  - name: "http"
    port: 8090
    targetPort: 8080
    nodePort: 30181
  - name: "8091"
    port: 8091
    targetPort: 80
    nodePort: 30185
  - name: "25"
    port: 25
    targetPort: 25
  selector:
    io.kompose.service: keycloak
  type: NodePort
  externalName: auth.egarteam.co.uk
